import{a as l,S as f,i as n}from"./assets/vendor-DXaqCXe3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();l.defaults.baseURL="https://pixabay.com/api/";const m=async i=>{const{data:r}=await l.get("",{params:{key:"49383072-7b2484b2a76b3ff56b3486fe5",q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}});return r.hits},c=document.querySelector(".gallery");document.querySelector(".loader");let g=new f(".gallery a",{captionsData:"alt",captionDelay:250});function y(){document.querySelector(".loader").classList.remove("hidden")}function h(){document.querySelector(".loader").classList.add("hidden")}function L(){c.innerHTML=""}function b(i){const r=i.map(({webformatURL:o,largeImageURL:a,tags:e,likes:t,views:s,comments:d,downloads:p})=>`
        <li class="gallery-item">
            <a href="${a}">
                <img src="${o}" alt="${e}" loading="lazy">
            </a>
             <ul class="info">
                <li class="description"><span>Likes</span> ${t}</li>
                <li class="description"><span>Views</span> ${s}</li>
                <li class="description"><span>Comments</span> ${d}</li>
                <li class="description"><span>Downloads</span> ${p}</li>
             </ul>
        </li>`).join("");c.insertAdjacentHTML("beforeend",r),g.refresh()}const u=document.querySelector(".form"),w=u.querySelector("input");u.addEventListener("submit",async i=>{i.preventDefault();const r=w.value.trim();if(!r){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}await L(),y();try{const o=await m(r);if(o.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}await b(o)}catch(o){n.error({title:"Error",message:"Oops! Something went wrong. Please try again later.",position:"topRight"}),console.error("Error fetching images:",o)}finally{h()}});
//# sourceMappingURL=index.js.map
